### ISSUE TITLE
Suggestions and requests

### ISSUE THREAD

**Issue by SiarMortal** [iOrange/sh2tex#1]
Hi, it's a great tool! Can you please make it dark for more pleasant viewing experience (most SH2 textures are pretty dark)?
And an export to PNG/TGA/BMP would be great too.

**Comment by iOrange** [comment]
Hi!

I'll try to add the dark theme to the app. Do you want it to follow your Windows settings or it being an option available inside the app?

As for the PNG/TGA/BMP/etc - adding them is easy, now the question is - do we need that? DDS is superior - it can contain compressed and uncompressed formats, and it unifies the format of the export and import functions.

It'll bloat the the UI a bit (how do we select the output format for the batch export) ?

I'll keep it simple for now, but can add if someone suggests nice solutions for the issues I've mentioned above.

**Comment by IlDucci** [comment]
Hi there! I'm the Spanish translator for the Enhanced Edition and I have also made a Spanish revision patch for both the PS2 and XBOX versions of the game, and I have quickly tested your tool with what I've got, so here are a bunch of comments and suggestions:

 - I agree that having BMP/PNG/TGA export/import support would be a great feature in terms of editing and forgetting for existing textures (which is my case). I understand that using DDS would help someone who wants to create from scratch pick the proper format.
 - In that regard, if I wanted to port my PS2 assets with your tool, DDS will not make the cut: you would need to preserve the existing palette or repalettize it, and DDS (and most likely, modern NVidia DDS exporters) is not compatible with PS2's 32bpp palette format, so TIM2 would need to be another option for exporting/importing. I had to make a mess with a script file (in ROMulan in my case) just to port my edited TIM2 textures to the clustered palette format for the PS2 textures. I understand that adding TIM2 support is a very different beast than adding PNG/BMP/TGA support, you would need to find other proper TIM2 handlers (Rainbow from Marco Calautti, perhaps?)
 - I'd like to see support to resize in the previewer screen images that are larger than the window so they fit into it. For example, EE's konami2048x2048.tex files will overflow anything other than 4k displays.

Now, as comments for your questions:

> I'll try to add the dark theme to the app. Do you want it to follow your Windows settings or it being an option available inside the app?

If I had to pick, both? As in, pick what's in Windows first, but have the option to override within the tool?

> It'll bloat the the UI a bit (how do we select the output format for the batch export) ?

Batch export to TGA/PNG/BMP/DDS could be a simple suboption before doing the actual batch job: original format (DDS) or pick an uncompressed one (TGA/PNG/BMP). That's the only real two choices there, without counting the TIM2 factor for PS2. For importing, though, that would be a bigger issue.

**Comment by iOrange** [comment]
@IlDucci thanks for your feedback!  I'll see what I can implement.
As for the preview resize -  you can use same hotkeys as in Photoshop -  `Ctrl`+`+`  to zoom in and `Ctrl`+`-` to zoom out.

**Comment by IlDucci** [comment]
> As for the preview resize - you can use same hotkeys as in Photoshop - `Ctrl`+`+` to zoom in and `Ctrl`+`-` to zoom out.

Oh, nice! If so, I'd be missing an equivalent with the mouse wheel, like Ctrl + Mouse up/Down. I missed out the zoom information in the lower bar.

**Comment by iOrange** [comment]
Okay, I think I can do dark theme. It's a bit troublesome but since it's not default - I'm okay with that.
I have couple of bugs to fix as well, and then I'll think on how to implement selecting the output format for the batch-export.

![image](https://github.com/iOrange/sh2tex/assets/7016607/540f84e8-d98a-4e8a-9656-d7599d4471f0)

**Comment by iOrange** [comment]
pushed 5ecfdcd9b47c3d79559771dc5e80694bac1406e6 to support dark theme

**Comment by iOrange** [comment]
+ added ability to save selected texture as PNG (with palette if any).
I guess that covers it, you can download the new release from here - https://github.com/iOrange/sh2tex/releases/tag/v1.1
