### ISSUE TITLE
Crtl + not zooming in

### ISSUE THREAD

**Issue by Polymega** [iOrange/sh2tex#2]
Hi there!

Playing with the tool some more, I noticed that `Crtl` + `-` will zoom out the texture, but `Crtl` + `+` does not zoom in on the texture. If you were to address this, might I also suggest adding `Ctrl` + `0` as "zoom to fit within current window space"? (This is what that shortcut does in Photoshop.)

Edit: Another small quirk I just noticed is, after opening a file, you must first click within the texture preview area before you're allowed to use the shortcut to zoom out.

**Comment by iOrange** [comment]
Hi @Polymega !

Thanks for your feedbacks!
I guess you're not using numerical pad on your keyboard (or you don't even have one) ?  In this case yes, it is actually `Ctrl`+`Shift`+`+`   :)

As for the `Ctrl`+`0` - that's interesting idea, will make it happen.

And thanks for the focus bug, will fix that as well (the image rendering panel isn't the one that has keyboard focus after opening the image).

**Comment by Polymega** [comment]
> In this case yes, it is actually Ctrl+Shift++ :)

Ah, I see. Yeah, I was playing with it on my laptop earlier which doesn't have a numpad. Would you think it better, for consistency's sake, that zoom in be the same key combo as zoom out (just changed from "-" to "+"... so `Ctrl` + `+`)?

If not, could you include Zoom In and Zoom Out somewhere as part of the top menu bar, with their shortcuts displayed off to the side? I mostly ask as all Adobe products use Ctrl -/+ for zoom out/in, and without the tool telling me, I'll never remember `Ctrl` + `Shift` + `+` to zoom in. 😅

**Comment by iOrange** [comment]
> Would you think it better, for consistency's sake, that zoom in be the same key combo as zoom out

Oh yes sure I'll make it better.  Will see if I can make it `Ctrl` + `MouseWheel` as well.

**Comment by SiarMortal** [comment]
Would be nice if zoom level persisted after switching to different texture/file.

**Comment by iOrange** [comment]
> Would be nice if zoom level persisted after switching to different texture/file.

TBH - I'm on the fence about this one.  Like I can see the benefit of not resetting zoom when switching between textures inside one file, but opening different file - I expect zoom to reset  (this is the default behaviour of most of other tools/viewers).

**Comment by iOrange** [comment]
Made improvements in commit 1c16a9c. Will build and push new release later today @Polymega @SiarMortal

**Comment by Polymega** [comment]
Thanks, iOrange! I'll keep an eye out on the tool's next build release. Hope you had a wonderful New Year!

**Comment by Polymega** [comment]
The new zoom handling is b-e-a-utiful. Such as pleasant experience to use! Thank you!

**Comment by iOrange** [comment]
> The new zoom handling is b-e-a-utiful. Such as pleasant experience to use! Thank you!

@Polymega thanks!  There was also a nice progress on PS2 support :)  https://github.com/iOrange/sh2tex/issues/3#issuecomment-1884101158
