### ISSUE TITLE
Interface suggestions

### ISSUE THREAD

**Issue by SiarMortal** [iOrange/sh2tex#4]
Would be cool to be able to open multiple files at once OR to switch between files with PgUp-PgDown keys.
So, for example, you open cb42.map, hit PgDown and cb43.map opened up next
.
Also would be nice if arrows always switched textures, no matter where the focus is.

**Comment by iOrange** [comment]
That's actually a good suggestion. Need to think about UI changes (to reflect the position inside the folder), but I'll implement this since I like it.

**Comment by Polymega** [comment]
May I also suggest that, since you're adding all these excellent shortcuts into the tool, to include them in the toolbar with their shortcuts keys shown off to the side? That way, people will know what shortcuts are available or as a refresher if they forgot them.

![image](https://github.com/iOrange/sh2tex/assets/27395260/d933485c-f071-496f-8fbe-e65a93339304)

**Comment by iOrange** [comment]
Yes, excellent suggestion! Thanks!

**Comment by Polymega** [comment]
Nice! Also, are you on Discord? If so, may I have your username to send you a friend request?

**Comment by iOrange** [comment]
@Polymega something like so, right ?
![image](https://github.com/iOrange/sh2tex/assets/7016607/2254bd46-dd35-4739-bdd5-ce8b13bf07a3)

**Comment by iOrange** [comment]
@Polymega @SiarMortal please download the latest version from https://github.com/iOrange/sh2tex/releases/tag/v1.3

**Comment by Polymega** [comment]
> @Polymega something like so, right ? ![image](https://private-user-images.githubusercontent.com/7016607/300040980-2254bd46-dd35-4739-bdd5-ce8b13bf07a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODg0MjQsIm5iZiI6MTcwNjI4ODEyNCwicGF0aCI6Ii83MDE2NjA3LzMwMDA0MDk4MC0yMjU0YmQ0Ni1kZDM1LTQ3MzktYmRkNS1jZThiMTNiZjA3YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMTY1NTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY0OWRiZTMxNGQ0NTA0ZjlmYTAzNDkxYTk3YTcyM2ZlYTNiNzMyMmJjMjliNmZjY2QwZDdkZWIyY2QzMDVmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VBjFT-zwT49PSADBOprTDGCT2DR998nWz0AfDYfNhIk)

Yep! Thank you!!
