### ISSUE TITLE
Software caches texture previews

### ISSUE THREAD

**Issue by Polymega** [iOrange/sh2tex#5]
Hi there!

I was doing some tests with Maria's model. For the game, she has several models as seen here:

![image](https://github.com/iOrange/sh2tex/assets/27395260/09c423d5-c65d-4a78-8bb3-1ead6e8500b6)

...and for all these models, they all use the same textures. Well, I found that if I replace a texture for one of these models, save, then open a new Maria model, the texture cache isn't flushed, so I'm seeing my edited texture on the new .mdl file, which I've yet to actually touch/do anything with.

**Comment by Polymega** [comment]
Update: There's a little more at play with this. While messing with the Maria .mdl files, for example, whenever I open a new one, the program isn't actually opening the new one and is instead staying on the previous file. I noticed this from the title bar in the software; despite opening new .mdl files, the name of the new file I opened isn't being shown here:

![image](https://github.com/iOrange/sh2tex/assets/27395260/9a8c6f1c-3f26-43b8-be5f-7135aeacac42)

It doesn't appear to do this for the `item` directory, as an example. This weird behavior also happens in the `jms` directory. 

Update 2: For the Maria .mdl files, the program will only open these two files (highlighted yellow):

![image](https://github.com/iOrange/sh2tex/assets/27395260/c18e2dee-4cd4-47b9-88ec-9dadd6ce217e)

**Comment by Polymega** [comment]
Nevermind, I'm a dummy. You did nothing wrong; the files it's not opening are not good to open. I didn't realize that and was confused as I incorrectly thought the program was opening them.

**Comment by iOrange** [comment]
Those other models I guess have no textures ?

**Comment by iOrange** [comment]
Maybe I should show just empty window then?  What would be the best behaviour ?

**Comment by Polymega** [comment]
Um, that's totally up to you. I will admit I was confused at first as the tool didn't provide any sort of feedback that the file was invalid for opening (so it just stayed on the previously opened file). That's what got me confused as I thought it opened it since nothing really changed upon trying.

Then again, I wasn't being all that observant at first. So it's totally up to you!
